server:
  port: 8081

spring:
  application:
    name: main-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  datasource:
    main:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://43.201.17.253:3306/kkobuk_main
      username: kkobuk
      password: rjqnr107
    meta:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://43.201.17.253:3306/meta
      username: kkobuk
      password: rjqnr107

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: aaaaaaaaaaabbbbbbbbbbbbbbccccccccccccceeeeeeeeeeeeeeekkkkkk
  data:
    redis:
      host: localhost
      port: 6379
      password: redis6379
      timeout: 60000
  mail:
    host: kkobuk@gmail.com
    port: 587
    username: kkobuk@gmail.com
    password: ssafy1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
