server:
  port: 8000

spring:
  application:
    name: apigatewayservice
  profiles:
    active: local
  config:
    import: optional:configserver:http://43.201.17.253:8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://43.201.17.253:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'